---
- name: Import the public key used by the package management system
  apt_key:
    url: "{{ mongodb_gpg_key }}"
    state: present
    
- name: Add APT repository
  apt_repository:
    repo: "deb https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/3.6 multiverse"
    update_cache: true

- name: Installing MongoDB-3.6
  apt:
   name: "mongodb-org,mongodb-org-server,mongodb-org-shell,mongodb-org-mongos,mongodb-org-tools"
   state: present

- name: inject kernel.mm.transparent_hugepage
  shell: |
      echo "never" >> /sys/kernel/mm/transparent_hugepage/enabled
      cat /sys/kernel/mm/transparent_hugepage/enabled

- name: inject kernel.mm.transparent_hugepage_defrag
  shell: |
      echo "never" >> /sys/kernel/mm/transparent_hugepage/defrag
      cat /sys/kernel/mm/transparent_hugepage/enabled

- name: inject kernel.mm.transparent_hugepage_defrag
  shell: |
      echo 0 > /sys/kernel/mm/transparent_hugepage/khugepaged/defrag
      cat /sys/kernel/mm/transparent_hugepage/enabled

- name: Install pymongo
  pip:
    name: pymongo==3.5.1
    state: present
